do {
    var a = 1



    // cho nay
    let b = try test_funtion(a)
 } catch {

 }
